#if !canImport(ObjectiveC)
import XCTest

extension BinaryenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryenTests = [
        ("testTypeNone", testTypeNone),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryenTests.__allTests__BinaryenTests),
    ]
}
#endif
